[phases.setup]
nixPkgs = ["python311", "nodejs", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt",
  "cd server && npm install"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python3 src/detection/main.py"
